CREATE DATABASE IF NOT EXISTS dbCulturales;
USE dbCulturales;

CREATE TABLE IF NOT EXISTS tblRegistro(
idRegistro INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
Nombre  VARCHAR(60) NOT NULL,
Boleta VARCHAR(11) NOT NULL,
correo VARCHAR(60) NOT NULL,
telefono VARCHAR(20) NOT NULL,
`gender` ENUM('M','F','NP') NOT NULL,
creditos INT(2),
`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
`active` TINYINT(1) NOT NULL DEFAULT '1'
)CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS tbGrupos(
idGrupo INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
horarios VARCHAR (20) NOT NULL,
cupo INT(2)
`active` TINYINT(1) NOT NULL DEFAULT '1'
)CHARSET=utf8mb4;



CREATE TABLE IF NOT EXISTS tbRlelacion(
idRelacion INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
idActividades INT UNSIGNED NOT NULL,
idGrupo INT UNSIGNED NOT NULL ,
FOREIGN KEY (idGrupo) REFERENCES tbGrupos(idGrupo)
);

CREATE TABLE IF NOT EXISTS tblActividades(
idActividades INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
Rama ENUM('fisicas','Culturales','Otros'),
idRelacion INT UNSIGNED NOT NULL,
activiades VARCHAR(30) NOT NULL,
idProfesor  INT UNSIGNED NOT NULL,
FOREIGN KEY (idRelacion) REFERENCES tbRlelacion(idRelacion)
)CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS tbMaetros(
idProfesor INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
Nombre VARCHAR(30),
Apellido_P VARCHAR(30),
Apellido_M VARCHAR(30),
correo VARCHAR(30),
Numero VARCHAR(30),
Gender ENUM('M','F','NP'),
`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
`active` TINYINT(1) NOT NULL DEFAULT '1'
)CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS tbCulturales(
  idCulturales INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  idRegistro INT UNSIGNED NOT NULL,
  idActividades INT UNSIGNED NOT NULL,
  nivel ENUM('BASICO','INTERMEDIO','AVANSADO','NULL'),
  `active` TINYINT(1) NOT NULL DEFAULT '1',
  FOREIGN KEY (idRegistro) REFERENCES tblRegistro(idRegistro),
  FOREIGN KEY (idActividades) REFERENCES tblActividades(idActividades)
)CHARSET=utf8mb4;
